"""add v3.8 diagnostic columns

Revision ID: 90b127cf0322
Revises: 394b2e1127fa
Create Date: 2026-06-24 20:52:28.006266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b127cf0322'
down_revision: Union[str, None] = '394b2e1127fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_for_sale', sa.Column('pred_v35', sa.Float(), nullable=True))
    op.add_column('properties_for_sale', sa.Column('pred_v38', sa.Float(), nullable=True))
    op.add_column('properties_for_sale', sa.Column('z_weight', sa.Float(), nullable=True))
    op.add_column('properties_for_sale', sa.Column('beta_tier', sa.String(length=16), nullable=True))
    op.add_column('properties_for_sale', sa.Column('cv_anchor', sa.Float(), nullable=True))
    op.add_column('properties_for_sale', sa.Column('cv_ratio_tier', sa.String(length=16), nullable=True))
    op.add_column('properties_for_sale', sa.Column('correction_used', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_for_sale', 'correction_used')
    op.drop_column('properties_for_sale', 'cv_ratio_tier')
    op.drop_column('properties_for_sale', 'cv_anchor')
    op.drop_column('properties_for_sale', 'beta_tier')
    op.drop_column('properties_for_sale', 'z_weight')
    op.drop_column('properties_for_sale', 'pred_v38')
    op.drop_column('properties_for_sale', 'pred_v35')
    # ### end Alembic commands ###
