"""initial schema

Revision ID: c078126fa190
Revises: 
Create Date: 2026-06-19 05:29:12.593455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c078126fa190'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_region'), 'import_batches', ['region'], unique=False)
    op.create_table('properties_for_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('predicted_list', sa.Float(), nullable=True),
    sa.Column('predicted_days', sa.Float(), nullable=True),
    sa.Column('comps_used', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('pred_vs_cv', sa.Float(), nullable=True),
    sa.Column('pred_vs_listing', sa.Float(), nullable=True),
    sa.Column('min_lot_m2', sa.Float(), nullable=True),
    sa.Column('max_addl_lots', sa.Float(), nullable=True),
    sa.Column('section_price_per_m2', sa.Float(), nullable=True),
    sa.Column('section_value_method', sa.String(length=32), nullable=True),
    sa.Column('services_cost', sa.Float(), nullable=True),
    sa.Column('total_subdivided_value', sa.Float(), nullable=True),
    sa.Column('uplift_vs_asking', sa.Float(), nullable=True),
    sa.Column('est_weekly_rent', sa.Float(), nullable=True),
    sa.Column('est_gross_yield', sa.Float(), nullable=True),
    sa.Column('annual_gross_rent', sa.Float(), nullable=True),
    sa.Column('annual_net_rent', sa.Float(), nullable=True),
    sa.Column('annual_mortgage', sa.Float(), nullable=True),
    sa.Column('annual_cashflow', sa.Float(), nullable=True),
    sa.Column('cash_on_cash', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('opportunity_score_pct', sa.Float(), nullable=True),
    sa.Column('best_strategy', sa.String(length=32), nullable=True),
    sa.Column('best_net_gain', sa.Float(), nullable=True),
    sa.Column('is_underpriced', sa.Boolean(), nullable=False),
    sa.Column('is_cashflow_positive', sa.Boolean(), nullable=False),
    sa.Column('is_subdividable', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('suburb', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('type_of_title', sa.String(length=64), nullable=True),
    sa.Column('zoning', sa.String(length=128), nullable=True),
    sa.Column('land_slope_contour', sa.String(length=64), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Integer(), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('floor_area_m2', sa.Float(), nullable=True),
    sa.Column('land_area_m2', sa.Float(), nullable=True),
    sa.Column('cv_numeric', sa.Float(), nullable=True),
    sa.Column('land_value_numeric', sa.Float(), nullable=True),
    sa.Column('improvement_value_numeric', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('slug_id', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('listing_date', sa.String(length=32), nullable=True),
    sa.Column('days_on_market', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fs_active_score', 'properties_for_sale', ['import_batch_id', 'opportunity_score_pct'], unique=False)
    op.create_index('ix_fs_active_suburb', 'properties_for_sale', ['import_batch_id', 'suburb'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_import_batch_id'), 'properties_for_sale', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_is_cashflow_positive'), 'properties_for_sale', ['is_cashflow_positive'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_is_subdividable'), 'properties_for_sale', ['is_subdividable'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_is_underpriced'), 'properties_for_sale', ['is_underpriced'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_opportunity_score'), 'properties_for_sale', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_opportunity_score_pct'), 'properties_for_sale', ['opportunity_score_pct'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_region'), 'properties_for_sale', ['region'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_slug_id'), 'properties_for_sale', ['slug_id'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_suburb'), 'properties_for_sale', ['suburb'], unique=False)
    op.create_index(op.f('ix_properties_for_sale_zoning'), 'properties_for_sale', ['zoning'], unique=False)
    op.create_table('properties_rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('weekly_rent', sa.Float(), nullable=True),
    sa.Column('listing_date_rent', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('suburb', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('type_of_title', sa.String(length=64), nullable=True),
    sa.Column('zoning', sa.String(length=128), nullable=True),
    sa.Column('land_slope_contour', sa.String(length=64), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Integer(), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('floor_area_m2', sa.Float(), nullable=True),
    sa.Column('land_area_m2', sa.Float(), nullable=True),
    sa.Column('cv_numeric', sa.Float(), nullable=True),
    sa.Column('land_value_numeric', sa.Float(), nullable=True),
    sa.Column('improvement_value_numeric', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('slug_id', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('listing_date', sa.String(length=32), nullable=True),
    sa.Column('days_on_market', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_rent_import_batch_id'), 'properties_rent', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_properties_rent_region'), 'properties_rent', ['region'], unique=False)
    op.create_index(op.f('ix_properties_rent_slug_id'), 'properties_rent', ['slug_id'], unique=False)
    op.create_index(op.f('ix_properties_rent_suburb'), 'properties_rent', ['suburb'], unique=False)
    op.create_index(op.f('ix_properties_rent_weekly_rent'), 'properties_rent', ['weekly_rent'], unique=False)
    op.create_index(op.f('ix_properties_rent_zoning'), 'properties_rent', ['zoning'], unique=False)
    op.create_index('ix_rent_comp', 'properties_rent', ['import_batch_id', 'suburb', 'beds'], unique=False)
    op.create_table('properties_sold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sold_date', sa.String(length=32), nullable=True),
    sa.Column('sale_method', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('suburb', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('type_of_title', sa.String(length=64), nullable=True),
    sa.Column('zoning', sa.String(length=128), nullable=True),
    sa.Column('land_slope_contour', sa.String(length=64), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Integer(), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('floor_area_m2', sa.Float(), nullable=True),
    sa.Column('land_area_m2', sa.Float(), nullable=True),
    sa.Column('cv_numeric', sa.Float(), nullable=True),
    sa.Column('land_value_numeric', sa.Float(), nullable=True),
    sa.Column('improvement_value_numeric', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('slug_id', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('listing_date', sa.String(length=32), nullable=True),
    sa.Column('days_on_market', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_sold_import_batch_id'), 'properties_sold', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_properties_sold_region'), 'properties_sold', ['region'], unique=False)
    op.create_index(op.f('ix_properties_sold_sale_price'), 'properties_sold', ['sale_price'], unique=False)
    op.create_index(op.f('ix_properties_sold_slug_id'), 'properties_sold', ['slug_id'], unique=False)
    op.create_index(op.f('ix_properties_sold_sold_date'), 'properties_sold', ['sold_date'], unique=False)
    op.create_index(op.f('ix_properties_sold_suburb'), 'properties_sold', ['suburb'], unique=False)
    op.create_index(op.f('ix_properties_sold_zoning'), 'properties_sold', ['zoning'], unique=False)
    op.create_index('ix_sold_comp', 'properties_sold', ['import_batch_id', 'suburb', 'beds', 'baths'], unique=False)
    op.create_index('ix_sold_zoning', 'properties_sold', ['import_batch_id', 'zoning'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sold_zoning', table_name='properties_sold')
    op.drop_index('ix_sold_comp', table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_zoning'), table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_suburb'), table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_sold_date'), table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_slug_id'), table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_sale_price'), table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_region'), table_name='properties_sold')
    op.drop_index(op.f('ix_properties_sold_import_batch_id'), table_name='properties_sold')
    op.drop_table('properties_sold')
    op.drop_index('ix_rent_comp', table_name='properties_rent')
    op.drop_index(op.f('ix_properties_rent_zoning'), table_name='properties_rent')
    op.drop_index(op.f('ix_properties_rent_weekly_rent'), table_name='properties_rent')
    op.drop_index(op.f('ix_properties_rent_suburb'), table_name='properties_rent')
    op.drop_index(op.f('ix_properties_rent_slug_id'), table_name='properties_rent')
    op.drop_index(op.f('ix_properties_rent_region'), table_name='properties_rent')
    op.drop_index(op.f('ix_properties_rent_import_batch_id'), table_name='properties_rent')
    op.drop_table('properties_rent')
    op.drop_index(op.f('ix_properties_for_sale_zoning'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_suburb'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_slug_id'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_region'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_opportunity_score_pct'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_opportunity_score'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_is_underpriced'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_is_subdividable'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_is_cashflow_positive'), table_name='properties_for_sale')
    op.drop_index(op.f('ix_properties_for_sale_import_batch_id'), table_name='properties_for_sale')
    op.drop_index('ix_fs_active_suburb', table_name='properties_for_sale')
    op.drop_index('ix_fs_active_score', table_name='properties_for_sale')
    op.drop_table('properties_for_sale')
    op.drop_index(op.f('ix_import_batches_region'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
