"""Validation gate: run our Python pipeline over the same 15,008 for-sale rows
the client priced in their Excel, compare row-by-row, and emit a markdown report.

This is the checkpoint where we decide whether the port is faithful enough to ship.
Target: >= 80% of rows within +/- 10% of client's Market_Value.
"""
from __future__ import annotations

import sys
import warnings as _w
from pathlib import Path

import numpy as np
import pandas as pd

_w.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parents[3]
XLSX = ROOT / "Ollie property.xlsx"
REPORT = Path(__file__).resolve().parents[1] / "validation_report.md"

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.pricing.comps import SoldDataset  # noqa: E402
from app.pricing.pipeline import run  # noqa: E402


def metric_diff(ours: pd.Series, theirs: pd.Series, label: str) -> dict:
    a = pd.to_numeric(ours, errors="coerce")
    b = pd.to_numeric(theirs, errors="coerce")
    mask = a.notna() & b.notna() & (b != 0)
    if not mask.any():
        return {"label": label, "n": 0}
    rel = (a[mask] - b[mask]) / b[mask].abs()
    abs_rel = rel.abs()
    return {
        "label": label,
        "n": int(mask.sum()),
        "median_abs_pct": float(abs_rel.median() * 100),
        "mean_abs_pct": float(abs_rel.mean() * 100),
        "within_5_pct": float((abs_rel <= 0.05).mean() * 100),
        "within_10_pct": float((abs_rel <= 0.10).mean() * 100),
        "within_20_pct": float((abs_rel <= 0.20).mean() * 100),
        "bias_pct": float(rel.mean() * 100),
    }


def main() -> int:
    print("Loading sold dataset (2016 sold_output) ...")
    sold_df = pd.read_excel(XLSX, sheet_name="2016 sold_output")
    print(f"  {len(sold_df)} sold rows")

    print("Loading for-sale dataset ...")
    fs_df = pd.read_excel(XLSX, sheet_name="for sale")
    print(f"  {len(fs_df)} for-sale rows")

    print("Building sold index ...")
    sold = SoldDataset(sold_df)

    print("Running full pipeline over all 15,008 rows (may take 1-2 min) ...")
    out = run(fs_df, sold)
    print(f"  Done. Output shape: {out.shape}")

    # === Compare key columns ===
    print()
    print("Computing diff metrics ...")

    metrics = [
        metric_diff(out["market_value"], fs_df["Market_Value"], "Market_Value"),
        metric_diff(out["max_addl_lots"], fs_df["Max_addl_lots"], "Max additional lots"),
        metric_diff(out["est_weekly_rent"], fs_df["Est_Weekly_Rent"], "Est weekly rent"),
        metric_diff(out["annual_cashflow"], fs_df["Annual_Cashflow"], "Annual cashflow"),
        metric_diff(out["best_net_gain"], fs_df["Best_Net_Gain"], "Best net gain (subdivision)"),
    ]

    # === Method distribution ===
    method_counts = out["confidence"].value_counts(dropna=False)

    # === Strategy match ===
    strategy_match = None
    if "Best_Strategy" in fs_df.columns:
        their_strat = fs_df["Best_Strategy"].fillna("(none)")
        our_strat = out["best_strategy"].fillna("(none)")
        agree = (their_strat == our_strat).sum()
        strategy_match = (int(agree), int(len(fs_df)), float(agree / len(fs_df) * 100))

    # === Worst-offender rows ===
    diff_mv = pd.to_numeric(out["market_value"], errors="coerce") - pd.to_numeric(fs_df["Market_Value"], errors="coerce")
    rel_mv = (diff_mv / pd.to_numeric(fs_df["Market_Value"], errors="coerce")).abs()
    worst = (
        pd.DataFrame({
            "address": fs_df["address"].astype(str).str[:40],
            "suburb": fs_df["suburb"],
            "type": fs_df["property_type"].astype(str).str[:30],
            "beds": fs_df["key_bedrooms"],
            "floor": fs_df["key_floor_area"],
            "theirs": fs_df["Market_Value"],
            "ours": out["market_value"],
            "rel_diff_pct": rel_mv * 100,
            "method": out["confidence"],
        })
        .dropna(subset=["rel_diff_pct"])
        .sort_values("rel_diff_pct", ascending=False)
        .head(20)
    )

    # === Write report ===
    lines: list[str] = []
    lines.append("# Validation gate — Python pipeline vs client's Excel")
    lines.append("")
    lines.append("Generated by `scripts/validate_against_excel.py`.")
    lines.append("")
    lines.append("## Headline accuracy (Market_Value)")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    mv = metrics[0]
    lines.append(f"| n compared | {mv['n']:,} |")
    lines.append(f"| Median absolute % error | **{mv['median_abs_pct']:.2f}%** |")
    lines.append(f"| Mean absolute % error (MAPE) | {mv['mean_abs_pct']:.2f}% |")
    lines.append(f"| Within ±5% | {mv['within_5_pct']:.1f}% |")
    lines.append(f"| Within ±10% | **{mv['within_10_pct']:.1f}%** |")
    lines.append(f"| Within ±20% | {mv['within_20_pct']:.1f}% |")
    lines.append(f"| Mean bias | {mv['bias_pct']:+.2f}% |")
    lines.append("")
    lines.append("## Other model outputs")
    lines.append("")
    lines.append("| Output | n | Median APE | Within ±10% | Within ±20% | Bias |")
    lines.append("|---|---|---|---|---|---|")
    for m in metrics[1:]:
        if m["n"] == 0:
            lines.append(f"| {m['label']} | 0 | — | — | — | — |")
        else:
            lines.append(
                f"| {m['label']} | {m['n']:,} | {m['median_abs_pct']:.2f}% | "
                f"{m['within_10_pct']:.1f}% | {m['within_20_pct']:.1f}% | "
                f"{m['bias_pct']:+.2f}% |"
            )
    lines.append("")
    if strategy_match:
        a, t, p = strategy_match
        lines.append(f"## Best Strategy agreement: **{a:,} / {t:,} ({p:.1f}%)**")
        lines.append("")
    lines.append("## Method / confidence distribution (ours)")
    lines.append("")
    lines.append("```")
    for k, v in method_counts.items():
        lines.append(f"  {k:<14} {v:>6,}")
    lines.append("```")
    lines.append("")
    lines.append("## Top 20 worst-offender Market_Value rows")
    lines.append("")
    lines.append("These are the rows where our number diverges most from theirs.")
    lines.append("")
    lines.append("| Address | Suburb | Type | Beds | Floor | Theirs | Ours | Diff % | Method |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for _, r in worst.iterrows():
        lines.append(
            f"| {r['address']} | {r['suburb']} | {r['type']} | "
            f"{int(r['beds']) if pd.notna(r['beds']) else '?'} | "
            f"{int(r['floor']) if pd.notna(r['floor']) else '?'} | "
            f"${r['theirs']/1000:.0f}k | ${r['ours']/1000:.0f}k | "
            f"{r['rel_diff_pct']:.1f}% | {r['method']} |"
        )
    lines.append("")

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nReport written to {REPORT}")

    # === Console summary ===
    print()
    print("=" * 60)
    print("VALIDATION GATE SUMMARY")
    print("=" * 60)
    print(f"Market_Value: median APE {mv['median_abs_pct']:.2f}%, within +/-10% = {mv['within_10_pct']:.1f}%")
    if mv["within_10_pct"] >= 80:
        print("PASS (>= 80% within +/-10%). Safe to proceed.")
        return 0
    print(f"REVIEW NEEDED ({mv['within_10_pct']:.1f}% within +/-10%, target 80%).")
    print(f"See {REPORT.name} for the top 20 outliers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
